# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
        with: 
          fetch-depth: 0

      # Runs a single command using the runners shell
      - name: Tag the latest commit
        run: |
             git config --global user.email "you@example.com"
             git config --global user.name "nutan"
             git tag -a v1.8 -m "initial"
            # git push origin --tags


      #qq Runs a set of commands using the runners shell
      - name: Create branch from the tag
        run: |
             git checkout -b v-1.8
            # git push --set-upstream origin v-1.3.6

      - name: Find second last commit
        run: |
             out=$(git rev-parse HEAD~1)
             echo $out

      - name: Find changed files
        run: |
            file=eval "git diff --name-only \${$out} HEAD~0"
            echo $file

      - name: Zip the files
        run: echo test

      - name: Initialise GoogleCli
        run: echo test

      - name: Upload the Google Composer
        run: echo test


      - name: Connection to Jfrog
        run: echo test

